{
	"patcher" : 	{
		"fileversion" : 1,
		"appversion" : 		{
			"major" : 6,
			"minor" : 0,
			"revision" : 4
		}
,
		"rect" : [ 309.0, 44.0, 663.0, 776.0 ],
		"bglocked" : 0,
		"openinpresentation" : 0,
		"default_fontsize" : 14.0,
		"default_fontface" : 0,
		"default_fontname" : "Optima Regular",
		"gridonopen" : 0,
		"gridsize" : [ 15.0, 15.0 ],
		"gridsnaponopen" : 0,
		"statusbarvisible" : 2,
		"toolbarvisible" : 1,
		"boxanimatetime" : 200,
		"imprint" : 0,
		"enablehscroll" : 1,
		"enablevscroll" : 1,
		"devicewidth" : 0.0,
		"description" : "",
		"digest" : "",
		"tags" : "",
		"boxes" : [ 			{
				"box" : 				{
					"fontname" : "Optima Regular",
					"fontsize" : 14.0,
					"id" : "obj-13",
					"linecount" : 5,
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 9.0, 574.404907, 570.0, 91.0 ],
					"text" : "\"Scalar\" speed determines the time interval (in milliseconds) between notes generated by the Pitch EG.  Unfortunately Max does note update the \"scalar speed\" values until after the stop/restart takes place … making adjustments to scalar speed will cause the start/stop audio check box to become unchecked.  I figured this would be a good way to remind users of the need to do this in order for Max to update the new value."
				}

			}
, 			{
				"box" : 				{
					"fontname" : "Optima Bold",
					"fontsize" : 14.0,
					"id" : "obj-1",
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 9.0, 551.110413, 159.0, 23.0 ],
					"text" : "Notes on \"Scalar Speed\""
				}

			}
, 			{
				"box" : 				{
					"comment" : "",
					"hidden" : 1,
					"id" : "obj-3",
					"maxclass" : "inlet",
					"numinlets" : 0,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"patching_rect" : [ 9.0, 9.0, 25.0, 25.0 ]
				}

			}
, 			{
				"box" : 				{
					"fontname" : "Optima Regular",
					"fontsize" : 14.0,
					"id" : "obj-4",
					"linecount" : 2,
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 9.0, 485.74234, 623.0, 40.0 ],
					"text" : "There are three range settings for these EGs full range, medium range, and LFO range. The purpose of these three settings is to make it easier to create contours in the graphic EG box in the various ranges."
				}

			}
, 			{
				"box" : 				{
					"fontname" : "Optima Bold",
					"fontsize" : 14.0,
					"id" : "obj-5",
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 9.0, 360.987732, 199.0, 23.0 ],
					"text" : "Notes on \"Smooth\" EG settings"
				}

			}
, 			{
				"box" : 				{
					"fontname" : "Optima Regular",
					"fontsize" : 14.0,
					"id" : "obj-6",
					"linecount" : 6,
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 9.0, 223.546005, 609.0, 108.0 ],
					"text" : "Screen Slider (also Mod Wheel) and \"scalar\" EG settings will generate discrete equal-tempered pitches at the rate designated by the \"scalar speed\" setting. But they will only be heard as discreet notes if portamento setting is also very low. Whenever a \"scalar\" EG setting is chosen from the menu the portamento setting is reset to zero milliseconds, but depending on the \"scalar speed\" setting (see below) it is possible that higher settings will produce both discrete scalar passages with a portamento slide between notes. Experiment to find the best settings for your desired effect."
				}

			}
, 			{
				"box" : 				{
					"fontname" : "Optima Regular",
					"fontsize" : 14.0,
					"id" : "obj-7",
					"linecount" : 5,
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 9.0, 383.595093, 593.0, 91.0 ],
					"text" : "\"Smooth\" EG settings are intended to work in conjunction with higher portatmento settings (and low scaler speed settings --see below). In fact, simply selecting one of the \"smooth\" EG settings will automatically reset the portamento value to 100 milliseconds. All the \"smooth\" EG's output on a purely linear \"Hz\" scale (as opposed to the non-linear equal tempered scalar setttings), so they are inherently smoother. But they will still sound \"grainy\" with too low a portamento setting."
				}

			}
, 			{
				"box" : 				{
					"fontname" : "Optima Bold",
					"fontsize" : 14.0,
					"id" : "obj-8",
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 9.0, 202.453995, 209.0, 23.0 ],
					"text" : "Notes on \"Scalar\" Pitch Controls"
				}

			}
, 			{
				"box" : 				{
					"fontname" : "Optima Regular",
					"fontsize" : 14.0,
					"id" : "obj-9",
					"linecount" : 3,
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 9.0, 677.208618, 583.0, 57.0 ],
					"text" : "In general, if you are using \"smooth\" EG setting you will probably want the lowest scalar speed setting (i.e. 20 milliseconds). If you are using one of the \"scalar\" settings you might want to use higher values to produces a slower more distinct flow of pitches."
				}

			}
, 			{
				"box" : 				{
					"fontname" : "Optima Regular",
					"fontsize" : 14.0,
					"id" : "obj-10",
					"linecount" : 6,
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 9.0, 39.466259, 561.0, 108.0 ],
					"text" : "Since this module has a somewhat quirky \"personality\" -- especially regarding oscillator frequency control -- I've written some detailed explanitory notes. If you are someone who likes to really understand what's going on *before* you play, then read on. If you're *not* that sort of person, stop reading now and start exploring what this synthesis module can do ... with the comforting knowlege that if you do get curious or confused about how/why things work the way they do, you'll be able to come back here and look for answers. Enjoy!"
				}

			}
, 			{
				"box" : 				{
					"fontname" : "Optima Regular",
					"fontsize" : 14.0,
					"id" : "obj-11",
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 9.0, 156.644165, 56.0, 23.0 ],
					"text" : "=m.p.="
				}

			}
 ],
		"lines" : [  ],
		"dependency_cache" : [  ]
	}

}
